name: Manual Docker build

on:
  workflow_dispatch:
    inputs:
      swa_bert_version:
        description: "SwaBERT version"
        required: true
      tags:
        description: "Tags (following Docker metadata syntax)"
        required: true

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        uses: ./.github/actions/docker-build
        with:
          swa_bert_version: ${{ inputs.swa_bert_version }}
          tags: ${{ inputs.tags }}
          registry: ghcr.io
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
